# CONTIKI_PROJECT = channel_sensing
# all: $(CONTIKI_PROJECT)

# DEFINES+=PROJECT_CONFIG=\"project-conf.h\"

# CONTIKI = ../..
# MAKE_NET = MAKE_NET_NULLNET
# TARGET_LIBFILES += -lm
# include $(CONTIKI)/Makefile.include


CONTIKI_PROJECT = channel_sensing
all: $(CONTIKI_PROJECT)
DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
MAKE_NET = MAKE_NET_NULLNET
TARGET_LIBFILES += -lm
CONTIKI = ../..
include $(CONTIKI)/Makefile.include